### ISSUE TITLE
`extract_strats` doesn't give the expected output-error

### ISSUE THREAD

**Issue by lucavd** [UBESP-DCTV/biorecur#2]
WE NEED TO UNDERSTAND ALL POSSIBLE WAYS TO DEFINE STRATA, WHICH ARE GOOD, WHICH ARE WRONG, AND HOW TO MANAGE THEM, I.E., EXTRACT STRATA OR SIGNAL A PROPER ERROR.

@lucavd wrote to the author to have some hints on how to reproduce the error (sending also our example files)

**Comment by lucavd** [comment]
Van: Luca Vedovelli <Luca.Vedovelli@ubep.unipd.it> 
Verzonden: vrijdag 15 maart 2024 12:15
Aan: Hof, Jasper <Jasper.Hof@radboudumc.nl>
CC: Corrado Lanera <corrado.lanera@ubep.unipd.it>
Onderwerp: RE: Including MMM in SPARE

Hi Jasper,
My colleague Corrado (that is a very expert developer) and I started to work on you package to implement MMM in it. They idea is to construct a CRAN-level package that implements both the methods and maybe some more (you will be one of the authors even in a possible paper, of course). 

Since your functions in the SPARE pkg consists in a single R file with no tests, we decided to separate the functions and add for every function a test to see if it works or not. 

We encountered a problem with the function MGres_check since we are unable to reproduce the error 'please include the strata once in the data frame' (here). We tried including the “strata” variable twice in the dataframe or other combinations, but the error doesn’t come out. 

I attach the files we use for testing the package. Can you modify (I guess) the pheno file (dataset_vedovelli_besta_bosisio.txt) in order to get the mentioned error?

Thank you and hope to hear from you soon!

L

**Comment by lucavd** [comment]
Hi Luca,

Thanks for your email, and good to hear that you are working on an implementation of MMM in SPARE! Of course I am happy to assist where possible.
The tests sound a great idea, and would be a good addition to the software.

I downloaded your files, and tried to produce the error. The error is indeed meant for dataframe for which the ‘strata’ variable is included twice in the data.
I have been able to produce the error with the code below, by giving two variables the same name for the stratum.

Hopefully this helps! And please let me know if I can be of any other help.

Best,

Jasper 



data <- read.table('dataset_vedovelli_besta_bosisio.txt', header = T)
data$Event = c(1,0,1,0)
data$subject = c(1,2,3,4)
data$Strat1 = c(1,1,2,2)
data$Strat2 = c(1,1,2,2)

colnames(data)[which(colnames(data) %in% c('Strat1','Strat2'))] = 'Stratum'

library(SPARE)
library(coxme)

fitme = coxme(Surv(Time_event, Event) ~ (1|subject) + strata(Stratum), data = data)

MGres_check(fitme, data)

**Comment by CorradoLanera** [comment]
@lucavd , questo _può_ succedere o è un controllo preventivo? Ovvero, un dataframe (una `tibble` in particolare) non può (e non dovrebbe...) avere mai per principio generale due colonne con lo stesso nome. Credo che il medesimo o analogo errore lo avremmo anche se avessimo due colonne che si chiamano "Event", ma non credo che `Surv` abbia una protezione esplicita rispetto a questo problema generale. Io proporrei di togliere l'errore e dare per scontato che il db sia fatto con standard minimi che per lo meno non compromettano l'uso generale, e mi limiterei a implementare solo test e protezioni specifiche per le nostre funzioni.

**Comment by lucavd** [comment]
Sono d'accordo, è una protezione troppo specifica.

**Comment by CorradoLanera** [comment]
@lucavd , in `extract_strats` 

https://github.com/UBESP-DCTV/biorecur/blob/44cf7cb4a4ad7d3dd1436bbc8bf0db6b40c85140/R/extract_strats.R#L10-L15 

Quando può accadere che `length(check_strat) < 2`? Può accadere?! Perchè la cosa non è minimamente considerata...

**Comment by lucavd** [comment]
se gli strati o i random effect non possono essere meno di due
